# Generated by Django 4.1 on 2022-12-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='cv',
            name='interests',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
